### ISSUE TITLE
Lexer support?

### ISSUE THREAD

**Issue by jackfirth** [AlexKnauth/colon-kw#2]
In DrRacket with racket 6.5, this program works fine:

``` racket
#lang colon-kw racket/base
(define (foo :bar bar) bar)
```

But `:bar` isn't yellow text like normal keywords are. How difficult would it be to provide a lexer that colors colon keywords the same as normal keywords?

**Comment by AlexKnauth** [comment]
I just tried this:
https://github.com/AlexKnauth/colon-kw/commit/45036f1652bfdc4a1a6beccf4e5062530b220baf
But it's doing weird things. For example in this program:

``` racket
#lang colon-kw racket
(define (f :x x) x)
```

If I edit it to add a space just before the `:x`, it now highlights the `(f  :x` as if it were a pair of parens, and it also highlights `(define (f  :x x)` as if it were a pair of parens. And it no longer thinks the last closing paren is a closing paren. Maybe I'm handling the offset wrong?

I have no idea how to do this.

**Comment by AlexKnauth** [comment]
Pull request #3 added this

**Comment by jackfirth** [comment]
Fantastic!
