### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by AlexKnauth** [AlexKnauth/colon-kw#4]
Contributor @lexi-lambda, I would like to add the MIT License to this repository.

If you agree, please post a message saying so, e.g. — "I hereby license my contributions to `colon-kw` under the MIT license."

**Comment by lexi-lambda** [comment]
To be honest, I forgot I ever even contributed anything to this repository. I will do you one better: I hereby release my contributions to `colon-kw` into the public domain.

**Comment by AlexKnauth** [comment]
Added in https://github.com/AlexKnauth/colon-kw/commit/dcde5d8a5ec5820bbb86ae5f5430236835b92d8a
